import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { cp, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

// Build outside the monorepo so its Effect overrides cannot rewrite this SDK's dependencies.
const root = dirname(fileURLToPath(import.meta.url));
const directory = await mkdtemp(join(tmpdir(), "zuse-executor-v2-"));
const run = (command, args) =>
	execFileSync(command, args, { cwd: directory, stdio: "inherit" });
try {
	const provenance = JSON.parse(
		await readFile(join(root, "vendor/provenance.json"), "utf8"),
	);
	const archive = await readFile(join(root, "vendor/upstream.tar.gz"));
	if (
		createHash("sha256").update(archive).digest("hex") !==
		provenance.sourceSha256
	)
		throw new Error("Executor source archive checksum mismatch");
	await cp(join(root, "toolchain"), directory, { recursive: true });
	await cp(join(root, "src"), join(directory, "adapter"), { recursive: true });
	run("tar", ["-xzf", join(root, "vendor/upstream.tar.gz")]);
	run("bun", ["install", "--frozen-lockfile", "--ignore-scripts"]);
	const aliases = {};
	for (const folder of provenance.packages) {
		const path = `packages/${folder}`;
		const manifest = JSON.parse(
			await readFile(join(directory, path, "package.json"), "utf8"),
		);
		for (const [subpath, target] of Object.entries(manifest.exports)) {
			if (typeof target === "string")
				aliases[manifest.name + (subpath === "." ? "" : subpath.slice(1))] =
					`./${path}/${target}`;
		}
	}
	await writeFile(
		join(directory, "tsconfig.json"),
		JSON.stringify({
			compilerOptions: {
				target: "ES2023",
				module: "ESNext",
				moduleResolution: "bundler",
				strict: true,
				exactOptionalPropertyTypes: true,
				skipLibCheck: true,
				noEmit: true,
				allowImportingTsExtensions: true,
				paths: Object.fromEntries(
					Object.entries(aliases).map(([key, value]) => [key, [value]]),
				),
			},
			files: ["adapter/bridge.ts"],
		}),
	);
	run("node", [
		"node_modules/typescript/bin/tsc",
		"--project",
		"tsconfig.json",
	]);
	const { build } = await import(
		pathToFileURL(join(directory, "node_modules/esbuild/lib/main.js")).href
	);
	const result = await build({
		absWorkingDir: directory,
		entryPoints: ["adapter/bridge.ts"],
		bundle: true,
		write: false,
		format: "esm",
		platform: "browser",
		target: "es2022",
		treeShaking: true,
		alias: aliases,
		legalComments: "inline",
		metafile: true,
		banner: {
			js: `// Generated by packages/executor-v2/build.mjs. Executor ${provenance.commit}. Do not edit.`,
		},
	});
	const output = result.outputFiles[0].contents;
	if (process.argv.includes("--check")) {
		const committed = await readFile(join(root, "vendor/runtime.mjs"));
		if (!committed.equals(Buffer.from(output)))
			throw new Error(
				"Executor bundle is stale; run bun run build in packages/executor-v2",
			);
	} else {
		await writeFile(join(root, "vendor/runtime.mjs"), output);
	}
	console.log(
		`Executor v2 typechecked and ${process.argv.includes("--check") ? "verified" : "built"} (${output.length} bytes).`,
	);
} finally {
	await rm(directory, { recursive: true, force: true });
}
