import type { PluginDefinition } from "@zuse/contracts";
import { PLUGIN_CATALOG_DATA } from "./plugin-catalog.data.ts";

export type PluginAuth = "oauth" | "none";

/** Server-owned entry. Clients never supply endpoints, headers, or client secrets. */
export interface CatalogPlugin extends PluginDefinition {
	readonly endpoint: string;
	/** OAuth discovery target when the endpoint carries provider query defaults. */
	readonly oauthDiscovery?: string;
	/** Feed hint. Without it, auth is probed when connecting. */
	readonly auth?: PluginAuth;
	readonly scopes?: readonly string[];
	readonly popularity: number;
}

/** Generated by `scripts/generate-plugin-catalog.ts`; featured first, then popularity. */
export const PLUGIN_CATALOG: readonly CatalogPlugin[] = PLUGIN_CATALOG_DATA;

const byId = new Map(PLUGIN_CATALOG.map((plugin) => [plugin.id, plugin]));
export const findCatalogPlugin = (id: string) => byId.get(id);

const publicCatalog: readonly PluginDefinition[] = PLUGIN_CATALOG.map(
	({ id, name, description, domain, category, featured }) => ({
		id,
		name,
		description,
		domain,
		category,
		featured,
	}),
);
export const publicPluginCatalog = () => publicCatalog;
